회원가입 구현
Instagram-Clone-Coding/Spring-Hexagonal-Instagram-Clone pull request #4
Opened 2023-05-22 11:30 UTC by bluetifulc

## 📌Linked Issues
- 

## ✏Change Details
### 누락된 패키지명 변경
 - 이전 작업한 패키지들의 앞에 `clone.instagram`이 빠져서 추가했습니다.

### 그래들 빌드 파일 수정
- `api`와 `data` 모듈은 `application` 모듈을 의존할 필요가 있어 추가했습니다.
  - `in`/`out`포트 인터페이스를 받아와야 합니다.
- 회원가입 api 테스트를 위해 `security` 종속성을 잠시 제거하였습니다. 로그인 구현 시 다시 추가하겠습니다.

### 회원가입 구현
- 만들면서 배우는 클린 아키텍처 책의 Github 코드와 유사한 형식, 네이밍으로 작성하였습니다.
- 예외처리, 응답코드와 같은 부분은 아직 작업이 되지 않아 다음 PR때 수정할 예정입니다.

## 💬Comment
### 다음 작업 예정 사항
- 공동 예외 처리, 응답 코드와 같은 작업
- 위 작업 이후 테스트 코드를 작성하고 로그인을 구현할 예정입니다.

### 고민점들
- 헥사고날 아키텍처로 작업하는 건 처음이라 여러 고민들이 있었습니다.
- 책에선 가능한 하나의 port에 하나의 기능(메서드)을 권장하였으나, 하나의 port 안에 여러 메서드를 넣는 것도 괜찮다고 생각했습니다. 예를들어 `LoadMemberByIdPort`내엔 `loadMemberById()`, `existsMemberById()` 두개의 연관된 메서드가 존재합니다.
- API 계층에서 application 로직 계층으로 넘겨주는 `Command` 내에 도메인 모델을 포함하였는데 괜찮은 방식일지?
- 현재 데이터(JPA) 계층과 application 로직 계층은 도메인 모델을 직접 주고 받는데 `Command`와 같은 DTO 객체가 필요할지? 그렇다면 어댑터 계층과는?

## 📑References
- 

## ✅Check List
- [x] 추가한 기능에 대한 테스트는 모두 완료하셨나요?
- [x] 코드 정렬(Ctrl + Alt + L), 불필요한 코드나 오타는 없는지 확인하셨나요?

2023-05-29 08:45 UTC, seonpilKim requested changes
리뷰가 늦어 죄송합니다. 

### 고민점들
> 헥사고날 아키텍처로 작업하는 건 처음이라 여러 고민들이 있었습니다.

> 책에선 가능한 하나의 port에 하나의 기능(메서드)을 권장하였으나, 하나의 port 안에 여러 메서드를 넣는 것도 괜찮다고 생각했습니다. 예를들어 LoadMemberByIdPort내엔 loadMemberById(), existsMemberById() 두개의 연관된 메서드가 존재합니다.

> API 계층에서 application 로직 계층으로 넘겨주는 Command 내에 도메인 모델을 포함하였는데 괜찮은 방식일지?
- 의존 순서가 올바르니 문제가 되진 않아 보여요. 다만, 개선할 포인트가 있어 보이네요. (리뷰 참고)

> 현재 데이터(JPA) 계층과 application 로직 계층은 도메인 모델을 직접 주고 받는데 Command와 같은 DTO 객체가 필요할지? 그렇다면 어댑터 계층과는?
- DTO 없이 도메인 모델을 주고 받아도 될 것 같아요.


PR당 파일 개수를 10~20개 정도로 유지해주시면 좋을 것 같아요!
파일 개수가 많으면 제가 놓치는 부분도 생길 수 있어서 감안해서 올려주시면 감사하겠습니다 :)

2023-05-29 08:45 UTC, seonpilKim commented on instagram-api/src/main/java/clone/instagram/member/controller/RegisterController.java
> +	}
Command에 따라 어떤 UseCase가 호출되는지 결정된다고 생각해보면,
Command는 UseCase에 완전 의존적인 관계라고 볼 수 있어요.

따라서, api 모듈에 private 메소드로 관리하기 보다는, UseCase 내부에 Command를 만드는 것이 더 바람직할 것 같아요.

조금 더 유연한 설계를 해보자면,
```java
public interface RegisterUseCase {

    boolean invoke(Command command);

    interface Command {
        class ToAccountInfo {

            private String username;
            private String password;
            private String name;
            private String email;
            
            // constructor
        }
    }    

}
```
위와 같이 UseCase에서 관리하고, Command를 interface로 변경하면, 하나의 UseCase안에 연관된 여러 메소드가 추가되더라도, 동일한 메소드 명(`invoke`)를 유지할 수 있고, 다형성(`Command`)을 이용해서 원하는 행동을 호출할 수 있게 돼요.

추가로 UseCase를 구현한 application 모듈에서는 Command interface의 어떤 구현체인지 구분하는 조건도 추가하면 좋겠죠.
코틀린에서는 when절을 이용해서 간편하게 처리했었어요.
```kotlin
// 예시 코드
    override fun invoke(command: RegisterUseCase.Command): boolean{
        return when (command) {
            is RegisterUseCase.Command.ToAccountInfo -> {
                // implement
            }
        }
    }
```

api 모듈은 아래와 같이 리팩토링하면 더 깔끔할 것 같아요.
```java
// RegisterController
	public ResponseEntity<Boolean> register(@RequestBody RegisterRequest registerRequest) {
	        final RegisterUseCase.Command accountInfo = RegisterUseCase.Command.ToAccountInfo(
		                registerRequest.getUsername(),
				registerRequest.getPassword(),
				registerRequest.getName(),
				registerRequest.getEmail()
		);
		return ResponseEntity.ok(toRegisterResponse(registerUseCase.register(accountInfo)));
	}
	
	private ResultResponse toRegisterResponse(boolean isRegistered) {
	    // implement
	}
```

2023-05-29 08:45 UTC, seonpilKim commented on instagram-api/src/main/java/clone/instagram/member/controller/RegisterController.java
> +	}
api 모듈에서 domain 모듈에 있는 객체를 생성해서 파라미터로 넘겨주는 것도 좋은 방법이에요.
다만, new 키워드를 이용해서 직접 객체를 생성하는 것 보다는, Member 클래스 내부에 `static factory method`를 만들어객체 생성을 한 곳에서 담당하고, 가독성 있는 네이밍을 사용한다면, 언제 해당 메소드를 이용하여 객체를 생성해야 하는지 더 명확해질 것 같아요.

2023-05-29 08:45 UTC, seonpilKim commented on instagram-data/src/main/java/clone/instagram/global/entity/ImageEntity.java
> +	}
if 절에 body가 1줄이더라도 { } 으로 감싸주세요.

2023-05-29 08:45 UTC, seonpilKim commented on instagram-api/src/main/java/clone/instagram/member/controller/RegisterController.java
> +	@ApiOperation(value = "회원가입")
한 줄 띄어주세요.

2023-05-29 08:45 UTC, seonpilKim commented on instagram-data/src/main/java/clone/instagram/member/adapter/MemberPersistentAdapter.java
> +}
Adapter 클래스는 adapter 모듈에 작성해 주세요.

2023-05-29 08:45 UTC, seonpilKim commented on instagram-data/src/main/java/clone/instagram/member/adapter/MemberPersistentAdapter.java
> +public class MemberPersistentAdapter implements LoadMemberByUsernamePort, SaveMemberPort {
data 모듈의 패키지 구조를 아래와 같이 변경하면 좋을 것 같아요.
```
/config (필요 시)
/jpa
    /repository
    /entity
        /global
        /member
    /mapper
/redis (필요 시)
    /repository
    /model
    ...   
```

2023-05-29 08:45 UTC, seonpilKim commented on instagram-data/src/main/java/clone/instagram/member/entity/MemberEntity.java
> +	private ImageEntity image;
Column명에 `member` prefix를 제거해보는 건 어떨까요?
members 테이블 내부 데이터에 member라는 prefix를 붙였을 때 얻는 이점이 크게 없는 것 같아요.

또, ImageEntity와 같이 속성을 재정의해줘야 하는 번거로움도 있구요.

2023-05-29 08:45 UTC, seonpilKim commented on instagram-data/src/main/java/clone/instagram/member/entity/MemberEntity.java
> +		);
매직 넘버는 상수로 분리하면 좋을 것 같아요.
외부 리소스들은 환경변수로 분리해도 좋을 것 같네요.

마찬가지로 static factory method pattern을 적용해보면 좋을 것 같아요.

2023-05-29 09:31 UTC, bluetifulc commented on instagram-data/src/main/java/clone/instagram/global/entity/ImageEntity.java
> +	}
이 부분은 전 프로젝트에서 그대로 복사해와서 체크를 안했네요. 수정하겠습니다

2023-05-29 09:32 UTC, bluetifulc commented on instagram-data/src/main/java/clone/instagram/member/entity/MemberEntity.java
> +	private ImageEntity image;
이 부분도 평소에 생각만 해보고 따로 말씀은 안드렸는데, 좋은 방법인 것 같습니다!

2023-05-29 09:36 UTC, bluetifulc commented on instagram-api/src/main/java/clone/instagram/member/controller/RegisterController.java
> +	}
> 정말 서로 연관이 깊다면, 하나의 port 안에 여러 메소드를 작성해도 문제될 건 없어 보여요. 다만 남용하지 않도록 주의해주세요.

`find`와 `exists` 두개 메서드를 묶는 정도로만 사용할 에정입니다.

변경된 파일의 경우 이전에 누락된 부분을 수정하기도 했고, 첫 로직 작성이라 한번에 흐름을 잡고 싶었습니다. 아마 다음 PR부턴  10개~20개정도 파일만 변경될 것 같습니다.

2023-05-29 09:40 UTC, seonpilKim commented on instagram-api/src/main/java/clone/instagram/member/controller/RegisterController.java
> +	}
아 깜박했는데, register과 같이 리소스를 생성하는 api는 리소스 생성 성공 시 201을 응답해주면 더 좋을 것 같아요~

2023-05-29 11:16 UTC, bluetifulc commented on instagram-api/src/main/java/clone/instagram/member/controller/RegisterController.java
> +	}
이 부분은 기록해두었다가 공동 Response 처리 때 적용하겠습니다

2023-05-29 11:27 UTC, bluetifulc commented on instagram-api/src/main/java/clone/instagram/member/controller/RegisterController.java
> +	}
> 위와 같이 UseCase에서 관리하고, Command를 interface로 변경하면, 하나의 UseCase안에 연관된 여러 메소드가 추가되더라도, 동일한 메소드 명(invoke)를 유지할 수 있고, 다형성(Command)을 이용해서 원하는 행동을 호출할 수 있게 돼요.

 잘 이해가 가지 않는데, UseCase안에 여러 메서드가 추가되는 경우는 어떤 경우가 있을까요?

2023-05-29 11:36 UTC, seonpilKim commented on instagram-api/src/main/java/clone/instagram/member/controller/RegisterController.java
> +	}
> 잘 이해가 가지 않는데, UseCase안에 여러 메서드가 추가되는 경우는 어떤 경우가 있을까요?

동일한(혹은 매우 연관된) 동작이지만, 명령(조건)에 따라 다른 로직으로 처리해야 하는 경우가 있겠네요.
```kotlin
// push 알람을 보내는 usecase
interface RevokePushTokenUseCase {
    @Transactional
    fun invoke(command: Command): PushToken

    sealed interface Command {
        data class FcmToken( // Google
            val userId: Long,
        ) : Command

        data class ApnsToken( // Apple
            val userId: Long,
        ) : Command
    }
}
```

2023-05-29 11:50 UTC, bluetifulc commented on instagram-api/src/main/java/clone/instagram/member/controller/RegisterController.java
> +	}
아아 넵 이해됐습니다.

자바 inner class의 경우 `static`으로 선언하는게 좋은 것으로 알고 있는데 이 경우엔 필요 없는걸까요?

2023-05-29 11:52 UTC, seonpilKim commented on instagram-api/src/main/java/clone/instagram/member/controller/RegisterController.java
> +	}
위 예시 코드들은 큰 틀만 보여드리려고 작성한거라 적절한 방식으로 변형해서 구현해주세요~ㅎㅎ

2023-05-30 06:24 UTC, bluetifulc commented
## 변경 사항
- 컨벤션 관련 수정
### data 모듈 패키지 구조 변경
- JPA 어댑터를 어댑터 모듈로 옮겼습니다.
  - JPA 어댑터 클래스 내에 주입 받는 클래스(Mapper, Repository)에 오류 밑줄이 발생하는데 저만 그런걸까요?
    -  스프링 정상 실행은 되는데, 찾아보니 2년쯤 전에 인텔리제이 버그가 있었다고 합니다.
- data 모듈의 패키지 구조를 변경하였습니다.
  - 일단 repository, mapper 패키지는 하위 패키지로 구분하지 않았는데, 추후에 너무 커진다 싶으면 분리하도록 하겠습니다. 
- JPA 의존성을 api로 변경
  -  JpaRepository를 사용하는 경우, implement대신 api로 빌드를 해야 정상 작동한다고 합니다.
  - 아마 querydsl쪽도 같은 방식일 것 같은데, 확인 후 수정하겠습니다.
### 스태틱 팩터리 메서드 적용
- image, member에 적용하였습니다.
- image의 경우 기본 이미지에 대한 값 주입을 설정 파일로 분리하였습니다.
### Command 관련 수정
- Command를 interface로 분리하고, 해당 interface를 상속받는 `AccountInfoCommand`를 작성하였습니다.
  - 올려주신 예시가 코틀린이라 빈 interface Command를 만들고 상속하는 것으로 이해했습니다. 제가 이해한 내용이 맞을까요?
    - 만약 빈 interface Command가 맞다면, Command는 global(common)로 뽑아내고, UseCase내에서 상속받아 구체 커맨드를 구현하는 것은 어떨까요? 빈 interface Command가 각 UseCase내에 있을 필요는 없다고 생각합니다.
      -  예를들면, 아래와 같은 형태입니다.
```java
// Command.java
interface Command{

}
```
```java
// RegisterUseCase.java
interface RegisterUseCase {

	boolean invoke(Command command);

	@Getter
	@AllArgsConstructor
	class AccountInfoCommand implements Command {

		private final Member member;

	}

}
```
   - 찾아보니 interface내에 클래스를 작성하는 경우엔 자동으로 `static`이 적용된다고 합니다.

2023-06-10 07:15 UTC, seonpilKim approved these changes

2023-06-10 07:15 UTC, seonpilKim commented on instagram-application/src/main/java/clone/instagram/member/port/in/RegisterUseCase.java
>  }
```java
public interface RegisterUseCase {

	boolean invoke(Command command);

	interface Command {

		@Getter
		@AllArgsConstructor
		class ToRegisterInfo implements Command {

			private final Member member;

		}

	}

}
```

- Command는 UseCase에 종속된 구조로 생각해주세요.
- Command 구현체는 interface 내부에 inner class로 관리하는 것을 권장합니다.
- 네이밍은 Command가 중복되니 생략하는 편이 좋아보입니다.
- RegisterInfo 의미가 회원을 등록하는 정보로 이해되는데, 이럴 때는 Member 자체를 멤버변수로 두는 것이 아니라, 각 정보들을 멤버 변수로 두고, Member 객체로 묶어서 반환하는 메소드를 활용해보면 어떨까요?


뒤늦게 코로나에 걸리는 바람에 리뷰가 많이 늦어졌네요.
다훈님도 코로나 조심하세요..

2023-06-10 15:50 UTC, bluetifulc commented on instagram-application/src/main/java/clone/instagram/member/port/in/RegisterUseCase.java
>  }
`Command` 인터페이스 내에서 바로 상속 받는 것이 가능했군요..!

각 정보를 멤버 변수로 입력 받고 `Member`객체로 묶는 `convert`함수는 Command 구현 클래스 안에 작성하면 될까요? 새로올린 커밋이 해당 방식입니다.

저도 위염으로 두달 넘게 고생 중인데 건강이 제일 중요한 것 같습니다.....

2023-06-12 03:55 UTC, merged